/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.laboratorio.software.jbom.gui;

import ar.laboratorio.software.jbom.domain.JBomDesktopClient;
import org.json.JSONObject;

/**
 *
 * @author francisco
 */
public class PantallaJuego extends javax.swing.JFrame {

    /**
     * Creates new form PantallaJuego
     */
    public PantallaJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        inputQuestion = new javax.swing.JTextField();
        optionOne = new javax.swing.JRadioButton();
        optionTwo = new javax.swing.JRadioButton();
        optionThree = new javax.swing.JRadioButton();
        optionFour = new javax.swing.JRadioButton();
        answerButton = new javax.swing.JButton();
        butonLeft = new javax.swing.JButton();
        botonRight = new javax.swing.JButton();
        botonDown = new javax.swing.JButton();
        butonUp = new javax.swing.JButton();
        messageInput = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/francisco/Documents/Facultad/LaboratorioDeSoftware/Jbom/JbomClienteDesk/src/main/resources/imagenes/bomba_50.png")); // NOI18N
        jLabel1.setText("Jugando JBom");

        jLabel3.setText("Pregunta: ");

        inputQuestion.setEditable(false);
        inputQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputQuestionActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionOne);
        optionOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionOneActionPerformed(evt);
            }
        });

        buttonGroup1.add(optionTwo);

        buttonGroup1.add(optionThree);

        buttonGroup1.add(optionFour);

        answerButton.setText("Responder");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputQuestion)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerButton)
                            .addComponent(optionFour)
                            .addComponent(optionThree)
                            .addComponent(optionTwo)
                            .addComponent(optionOne))
                        .addGap(0, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(optionOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionThree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerButton)
                .addGap(18, 18, 18))
        );
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(inputQuestion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(optionOne, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(optionTwo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(optionThree, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(optionFour, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(answerButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        butonLeft.setIcon(new javax.swing.ImageIcon("/home/francisco/Documents/Facultad/LaboratorioDeSoftware/Jbom/JbomClienteDesk/src/main/resources/imagenes/left_arrow.png")); // NOI18N
        butonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonLeftActionPerformed(evt);
            }
        });

        botonRight.setIcon(new javax.swing.ImageIcon("/home/francisco/Documents/Facultad/LaboratorioDeSoftware/Jbom/JbomClienteDesk/src/main/resources/imagenes/right_arrow.png")); // NOI18N
        botonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRightActionPerformed(evt);
            }
        });

        botonDown.setIcon(new javax.swing.ImageIcon("/home/francisco/Documents/Facultad/LaboratorioDeSoftware/Jbom/JbomClienteDesk/src/main/resources/imagenes/down_arrow.png")); // NOI18N
        botonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDownActionPerformed(evt);
            }
        });

        butonUp.setIcon(new javax.swing.ImageIcon("/home/francisco/Documents/Facultad/LaboratorioDeSoftware/Jbom/JbomClienteDesk/src/main/resources/imagenes/up_arrow.png")); // NOI18N
        butonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(messageInput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1)
                            .addComponent(botonDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(butonUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(messageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butonLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDown, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonLeftActionPerformed
        JBomDesktopClient.getInstance().selectWestGate();
        this.disableBottons();
        this.cleanQuestion();
    }//GEN-LAST:event_butonLeftActionPerformed

    private void butonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonUpActionPerformed
        JBomDesktopClient.getInstance().selectNorthGate();
        this.disableBottons();
        this.cleanQuestion();
    }//GEN-LAST:event_butonUpActionPerformed

    private void inputQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputQuestionActionPerformed
        
    }//GEN-LAST:event_inputQuestionActionPerformed

    private void optionOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionOneActionPerformed
        
    }//GEN-LAST:event_optionOneActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        if(optionOne.isSelected())
            JBomDesktopClient.getInstance().answerdQuestion(optionOne.getText());
        if(optionTwo.isSelected())
            JBomDesktopClient.getInstance().answerdQuestion(optionTwo.getText());
        if(optionThree.isSelected())
            JBomDesktopClient.getInstance().answerdQuestion(optionThree.getText());
        if(optionFour.isSelected())
            JBomDesktopClient.getInstance().answerdQuestion(optionFour.getText());
        this.disableUI();
    }//GEN-LAST:event_answerButtonActionPerformed

    private void botonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDownActionPerformed
        JBomDesktopClient.getInstance().selectSouthGate();
        this.disableBottons();
        this.cleanQuestion();
    }//GEN-LAST:event_botonDownActionPerformed

    private void botonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRightActionPerformed
        JBomDesktopClient.getInstance().selectEastGate();
        this.disableBottons();
        this.cleanQuestion();
    }//GEN-LAST:event_botonRightActionPerformed

    public void publishMessage(String message){
        messageInput.setText(message);
    }
    
    public void disableUI(){
        inputQuestion.setEnabled(false);
        optionOne.setEnabled(false);
        optionTwo.setEnabled(false);
        optionThree.setEnabled(false);
        optionFour.setEnabled(false);
        answerButton.setEnabled(false);
    }
    
    public void enableBottons(){
        butonUp.setEnabled(true);
        botonDown.setEnabled(true);
        botonRight.setEnabled(true);
        butonLeft.setEnabled(true);
    }
    
    public void disableBottons(){
        butonUp.setEnabled(false);
        botonDown.setEnabled(false);
        botonRight.setEnabled(false);
        butonLeft.setEnabled(false);  
    }
    
    public void enableUI(){
        inputQuestion.setEnabled(true);
        optionOne.setEnabled(true);
        optionTwo.setEnabled(true);
        optionThree.setEnabled(true);
        optionFour.setEnabled(true);
        answerButton.setEnabled(true);
    }
    
    public void showQuestion(String question){
        JSONObject questionJSON = new JSONObject(question);
        inputQuestion.setText(questionJSON.getString("pregunta"));
        optionOne.setText(questionJSON.getString("opcionUno"));
        optionTwo.setText(questionJSON.getString("opcionDos"));
        optionThree.setText(questionJSON.getString("opcionTres"));
        optionFour.setText(questionJSON.getString("opcionCuatro"));
    }
    
    public void cleanQuestion(){
        inputQuestion.setText("");
        optionOne.setText("");
        optionTwo.setText("");
        optionThree.setText("");
        optionFour.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JButton botonDown;
    private javax.swing.JButton botonRight;
    private javax.swing.JButton butonLeft;
    private javax.swing.JButton butonUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField messageInput;
    private javax.swing.JRadioButton optionFour;
    private javax.swing.JRadioButton optionOne;
    private javax.swing.JRadioButton optionThree;
    private javax.swing.JRadioButton optionTwo;
    // End of variables declaration//GEN-END:variables
}
